"""kb

Revision ID: 77673cee8fa7
Revises: dcdb17ebf911
Create Date: 2025-10-21 08:55:03.675445

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '77673cee8fa7'
down_revision = 'dcdb17ebf911'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_folders_owner_name', 'knowledge_base_folders', ['owner_id', 'name'], unique=False)
    op.create_table('knowledge_base_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['knowledge_base_folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_entries_folder_active', 'knowledge_base_entries', ['folder_id', 'is_active'], unique=False)
    op.create_index('ix_kb_entries_owner_active', 'knowledge_base_entries', ['owner_id', 'is_active'], unique=False)
    op.create_table('agent_knowledge_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('entry_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entry_id'], ['knowledge_base_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kb_assignments_agent_enabled', 'agent_knowledge_assignments', ['agent_id', 'enabled'], unique=False)
    op.create_index('ix_kb_assignments_agent_entry', 'agent_knowledge_assignments', ['agent_id', 'entry_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kb_assignments_agent_entry', table_name='agent_knowledge_assignments')
    op.drop_index('ix_kb_assignments_agent_enabled', table_name='agent_knowledge_assignments')
    op.drop_table('agent_knowledge_assignments')
    op.drop_index('ix_kb_entries_owner_active', table_name='knowledge_base_entries')
    op.drop_index('ix_kb_entries_folder_active', table_name='knowledge_base_entries')
    op.drop_table('knowledge_base_entries')
    op.drop_index('ix_kb_folders_owner_name', table_name='knowledge_base_folders')
    op.drop_table('knowledge_base_folders')
    # ### end Alembic commands ###
