"""description

Revision ID: 7c6352ba2722
Revises: 77673cee8fa7
Create Date: 2025-10-21 12:16:15.072713

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7c6352ba2722'
down_revision = '77673cee8fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lifetime_granted', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lifetime_used', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_credit_accounts_user_id', 'credit_accounts', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('my_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credit_transactions_created_at', 'credit_transactions', ['created_at'], unique=False)
    op.create_index('ix_credit_transactions_type', 'credit_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_credit_transactions_user_id', 'credit_transactions', ['user_id'], unique=False)
    op.add_column('agent_runs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('agent_runs', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('agent_runs', sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'model_used')
    op.drop_column('agent_runs', 'total_cost')
    op.drop_column('agent_runs', 'output_tokens')
    op.drop_column('agent_runs', 'input_tokens')
    op.drop_index('ix_credit_transactions_user_id', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_type', table_name='credit_transactions')
    op.drop_index('ix_credit_transactions_created_at', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index('ix_credit_accounts_user_id', table_name='credit_accounts')
    op.drop_table('credit_accounts')
    # ### end Alembic commands ###
