"""description1

Revision ID: ceef03e5eec0
Revises: ae4b8be24fae
Create Date: 2025-10-16 11:04:28.592319

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ceef03e5eec0'
down_revision = 'ae4b8be24fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_runs_agent_version_id_fkey'), 'agent_runs', type_='foreignkey')
    op.drop_constraint(op.f('agent_runs_agent_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'agent_runs', 'agent_versions', ['agent_version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_runs_agent_id_fkey'), 'agent_runs', 'agents', ['agent_id'], ['id'])
    op.create_foreign_key(op.f('agent_runs_agent_version_id_fkey'), 'agent_runs', 'agent_versions', ['agent_version_id'], ['id'])
    # ### end Alembic commands ###
