"""description1

Revision ID: dcdb17ebf911
Revises: ceef03e5eec0
Create Date: 2025-10-16 11:05:49.340913

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dcdb17ebf911'
down_revision = 'ceef03e5eec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
